name: Dependabot

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: code de checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.1'
      - name: Setup Dependabot
        uses: dependabot/dependabot-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
